### ISSUE TITLE
unable to connect to python publisher

### ISSUE THREAD

**Issue by Fethi-Hamdani** [tmtong/roslibdart#1]
ros listener on flutter app doesn't seem to work, i have a python publisher running on 192.168.1.8:9090
here is my app code
`    ros = Ros(url: 'ws://192.168.1.8:9090');
    chatter = Topic(
      ros: ros!,
      name: '/topic',
      type: "std_msgs/String",
    );
    ros!.connect();
    await chatter!.subscribe(subscribeHandler);`

**Comment by tmtong** [comment]
Sorry for the late reply. Can you tell me more detail ? Have your start your Ros bridge ? Have you start a publisher on the Ros side ? What error message do you  have ?  Does using the sample code I have work for you ? Does the sample code work on the same machine ? Is 192.168.1.8 pingable from your subscriber ? Is there a firewall? Can two python subscriber and prescriber can talk to each other ?
